# Generated by Django 4.1 on 2022-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=200, verbose_name='Наименование банка')),
                ('term_min', models.IntegerField(default=0, verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.IntegerField(default=0, verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(default=0, verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(default=0, verbose_name='Ставка, ДО')),
                ('payment_min', models.BigIntegerField(default=0, verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.BigIntegerField(default=0, verbose_name='Сумма кредита, ДО')),
            ],
        ),
    ]
