# Generated by Django 4.1 on 2022-08-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mortgage',
            new_name='Ipoteka',
        ),
    ]
